### ISSUE TITLE
Not related to this project

### ISSUE THREAD

**Issue by hakim1901** [rodrigrichrod/dictionary#1]
Hi @rodrigrichrod  I didn't get any other way to contact you, sorry for that, I need you help regarding Cypress integration with msnodesqlv8, I saw you raised an issue with Cypress, I want to know have you manage to incorporate msnodesqlv8 with Cypress. I am facing lot of issue and I am stuck. Your little help is very appreciated. I need to connect SQL server with windows authentication. Thanks!

**Comment by rodrigrichrod** [comment]
@hakim1901  Yes, I got it working. 

1. You will need to add mssql AND msnodesqlv8 as your node dependencies. 
2. In your plugins section modify your index.js to include the following(just add in your db name and server name to the appropriate strings):

const sql = require("mssql/msnodesqlv8");

module.exports = (on, config) => {
on( 'task', {
runquery(query){
const conn = new sql.ConnectionPool({
database: "",
server: "",
driver: "msnodesqlv8",
options: {
trustedConnection: true
}
});
return new Promise((resolve)=>{
conn.connect().then(() => {
conn.request().query(query, (err, result) => {
conn.close();
resolve(result)
})
})
setTimeout(()=> resolve(null), 3000)
});
}
});
}

3. Add this to your cypress.json:
"nodeVersion" : "system"

That should allow you to load up cypress test runner without any problems.  

Now you can use cy.task('runquery', yourQueryHere) in your test.

Let me know how it goes :)

**Comment by hakim1901** [comment]
Thanks a lot @rodrigrichrod. It worked for me. You made my Day !!
